### ISSUE TITLE
Implementación de clases para el modelo

### ISSUE THREAD

**Issue by Avoi1d** [arsa-dev/OMP-Logic#9]
Hola @arsa-dev, me ha asignado este repositorio para trabajar el objetivo 2. Voy a utilizar este issue para comunicar contigo y para el desarrollo del objetivo. He visto que has abierto tú un issue también, pero he decidido abrir uno para poder referirme a las tareas en mi futuro PR.
## Lista de tareas:
* [x] Decidir el lenguaje de programación: he visto en el otro issue que has decidido usar typescript, me parece perfecto. Aunque no se si has comentado con el profesor de tu decisión.
* [x] Decidir la estructura de los directorios y ficheros.
* [x] Determinar los objetos valor y las entidades.
* [x] Implementación.

**Comment by arsa-dev** [comment]
Hola @vdeq79, sí he comentado con el profesor en un par de ocasiones en clase el tema del lenguaje. En cuanto a la estructura de ficheros, yo me decantaría por una estructura MVC típica, aunque en este objetivo solamente vamos a definir el modelo de información por lo que todos estos modelos se podrían encontrar bajo la carpeta `models`. En cuanto a los objetos a implementar y una breve descripción sobre ellos se puede encontrar [en el readme](https://github.com/arsa-dev/OMP-Logic#objetos-de-negocio). Estoy atento ante cualquier aclaración adicional que pueda ser necesaria en cuanto a la definición de modelos o detalle de implementación.

**Comment by Avoi1d** [comment]
Hola @arsa-dev, he hecho un pull request #10  con la primera aproximación que he hecho del modelo. Tengo todavía que añadir el yaml pero me vendría bien si pudieras hecharle un vistazo (en la parte de órdenes de fabricación creo que tengo que modificarlo porque no se si se ajusta a lo que quieres). También te quería pedirte que añadieras este issue al M0, saludos.

**Comment by arsa-dev** [comment]
> Hola @arsa-dev, he hecho un pull request #10 con la primera aproximación que he hecho del modelo. Tengo todavía que añadir el yaml pero me vendría bien si pudieras hecharle un vistazo (en la parte de órdenes de fabricación creo que tengo que modificarlo porque no se si se ajusta a lo que quieres). También te quería pedirte que añadieras este issue al M0, saludos.

Hola @vdeq79, disculpa la demora, lo reviso a continuación en el propio pull request.

**Comment by Avoi1d** [comment]
Hola @arsa-dev, gracias por las aclaraciones de https://github.com/arsa-dev/OMP-Logic/pull/10#discussion_r1002436102. He realizado los cambios que me habías pedido el jueves pero me queda algunas dudas sobre cómo vas a llevar a cabo tu lógica de negocio para tenerlo en cuenta en el modelado: 
- ¿vas a tener en cuenta la diferencia entre operarios a la hora de realizar unas determinadas operaciones (lo cual implicaría la creación de una clase operario)? 
- Y en ese caso, habría también que relacionar el operario con el orden de fabricación que está trabajando (una relación uno a muchos (o muchos a muchos?) que va cambiando a la largo del tiempo).
- En caso contrario (suponiendo que cada operario trabaja con un ritmo uniforme para cada operación), trabajar directamente sobre las operaciones con nuevos campos (estado, nº de operarios trabajando y duración dado el número de operarios).

**Comment by arsa-dev** [comment]
Al menos en una primera instancia no tengo pensado implementar lógica para
calculo de agregados por operarios por lo que no sería necesario
implementar esa clase. De ser necesario podría implementar este modelo en
un futuro yo mismo. Yo creo que estaría todo excepto la elección del
runtime.
